# Generated by Django 4.1 on 2022-09-10 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0006_alter_doc_username_alter_pharma_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ideal_bmi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_range', models.IntegerField(choices=[(10, 10), (20, 20), (30, 30), (40, 40), (50, 50), (60, 60), (70, 70), (80, 80), (90, 90), (100, 100)])),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=20)),
                ('ideal_weight', models.IntegerField(choices=[(10, 10), (20, 20), (30, 30), (40, 40), (50, 50), (60, 60), (70, 70), (80, 80), (90, 90), (100, 100)])),
                ('ideal_height', models.IntegerField(choices=[(70, 70), (90, 90), (110, 110), (130, 130), (150, 150), (170, 170), (190, 190), (200, 200), (220, 220), (240, 240)])),
                ('ideal_bmi', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='bmi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('user_weight', models.IntegerField()),
                ('user_bmi', models.IntegerField()),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.user')),
            ],
        ),
    ]
