# Generated by Django 4.1 on 2022-09-10 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmi',
            name='gender',
            field=models.CharField(default='male', max_length=20),
        ),
        migrations.AddField(
            model_name='bmi',
            name='user_height',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='bmi',
            name='age',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='bmi',
            name='user_bmi',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='bmi',
            name='user_weight',
            field=models.IntegerField(default=10),
        ),
    ]
