# Generated by Django 4.1 on 2022-10-13 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_doc_image'),
        ('bmi', '0002_bmi_gender_bmi_user_height_alter_bmi_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmi',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.user', to_field='username'),
        ),
    ]
