# Generated by Django 4.1 on 2022-10-12 16:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 12, 16, 17, 19, 851636, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='timeline_doc',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 12, 16, 17, 19, 851636, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='timeline_pharma',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 12, 16, 17, 19, 851636, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
