# Generated by Django 4.1 on 2022-10-13 12:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_doc_image'),
        ('timeline', '0005_alter_timeline_datetime_alter_timeline_doc_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 13, 12, 22, 15, 488826, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.user', to_field='username'),
        ),
        migrations.AlterField(
            model_name='timeline_doc',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 13, 12, 22, 15, 488826, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='timeline_doc',
            name='docId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.doc', to_field='username'),
        ),
        migrations.AlterField(
            model_name='timeline_pharma',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 13, 12, 22, 15, 496830, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='timeline_pharma',
            name='pharmaId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.pharma', to_field='username'),
        ),
    ]
