# Generated by Django 4.1 on 2022-09-03 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(5, 'Very Good'), (4, 'Good'), (3, 'Average'), (2, 'Not Good'), (1, 'Bad')])),
                ('message', models.CharField(max_length=500)),
            ],
        ),
    ]
