# Generated by Django 4.1 on 2022-09-03 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='nationwideDel',
        ),
        migrations.AddField(
            model_name='contact',
            name='solved',
            field=models.BooleanField(default=False),
        ),
    ]
