# Generated by Django 4.1 on 2022-10-12 16:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senderId', models.IntegerField()),
                ('receiverId', models.IntegerField()),
                ('message', models.CharField(max_length=256)),
                ('date', models.DateField(default=datetime.datetime(2022, 10, 12, 16, 27, 38, 214770, tzinfo=datetime.timezone.utc), null=True)),
            ],
        ),
    ]
