# Generated by Django 4.1 on 2022-10-12 16:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 10, 12, 16, 51, 29, 215903, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='receiverId',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='chat',
            name='senderId',
            field=models.CharField(max_length=256),
        ),
    ]
