# Generated by Django 4.1 on 2022-10-13 04:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_doc_image'),
        ('chat', '0003_alter_chat_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 10, 13, 4, 53, 26, 98513, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='receiverId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='register.user'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='senderId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='register.user'),
        ),
    ]
