# Generated by Django 4.1 on 2022-10-16 18:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_chat_date_alter_chat_receiverid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 10, 16, 18, 13, 53, 974022, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
