# Generated by Django 4.1 on 2022-09-26 06:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 26, 6, 21, 26, 672297, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
