# Generated by Django 4.1 on 2022-09-30 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todoitem_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 30, 14, 10, 42, 813726, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
