# Generated by Django 4.1 on 2022-10-01 06:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_alter_todoitem_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 1, 6, 17, 17, 514717, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
