# Generated by Django 4.1 on 2022-10-03 06:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0011_alter_todoitem_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 3, 6, 56, 54, 596010, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
