# Generated by Django 4.1 on 2022-10-13 12:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0022_alter_todoitem_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 13, 12, 18, 20, 867160, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='todo_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.todolist', to_field='title'),
        ),
    ]
