# Generated by Django 4.1 on 2022-10-16 18:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0023_alter_todoitem_created_date_alter_todoitem_todo_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 16, 18, 13, 53, 915993, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
