# Generated by Django 4.1 on 2022-09-09 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=200)),
                ('time', models.CharField(choices=[('10:00-11:00', '10:00-11:00'), ('11:00-12:00', '11:00-12:00'), ('12:00-1:00', '12:00-1:00'), ('1:00-2:00', '1:00-2:00'), ('2:00-3:00', '2:00-3:00'), ('3:00-4:00', '3:00-4:00'), ('4:00-5:00', '4:00-5:00'), ('5:00-6:00', '5:00-6:00')], max_length=500)),
                ('day', models.CharField(choices=[('MONDAY', 'MONDAY'), ('TUESDAY', 'TUESDAY'), ('WEDNESDAY', 'WEDNESDAY'), ('THURSDAY', 'THURSDAY'), ('FRIDAY', 'FRIDAY'), ('SATURDAY', 'SATURDAY'), ('SUNDAY', 'SUNDAY')], max_length=500)),
                ('request', models.TextField(max_length=500)),
                ('status', models.CharField(choices=[(0, 'Pending'), (1, 'Accepted'), (2, 'Rejected')], default=0, max_length=500)),
                ('doctorId', models.IntegerField(null=True)),
            ],
        ),
    ]
