# Generated by Django 4.1 on 2022-09-09 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctorId',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
