# Generated by Django 4.1 on 2022-09-25 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_alter_appointment_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='address',
        ),
    ]
