# Generated by Django 4.1 on 2022-10-06 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_doc_image'),
        ('appointment', '0007_alter_appointment_doctorid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctorId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='register.doc'),
        ),
    ]
