# Generated by Django 4.1 on 2022-10-13 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_doc_image'),
        ('appointment', '0011_alter_appointment_doctorid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctorId',
            field=models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, to='register.doc', to_field='username'),
        ),
    ]
