# Generated by Django 4.1 on 2022-09-07 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disease', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remedies_1', models.CharField(max_length=50)),
                ('remedies_2', models.CharField(max_length=50)),
                ('remedies_3', models.CharField(max_length=50)),
                ('idd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disease.disease')),
            ],
        ),
    ]
