# Generated by Django 4.1 on 2022-10-13 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0001_initial'),
        ('treatment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='idd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disease.disease', to_field='name'),
        ),
    ]
