# Generated by Django 4.1 on 2022-09-01 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='doc',
            name='experience',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='doc',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pharma',
            name='licenseNumber',
            field=models.IntegerField(),
        ),
    ]
