# Generated by Django 4.1 on 2022-09-30 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharma',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='register/imgaes'),
        ),
    ]
