# Generated by Django 4.1 on 2022-09-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='medhistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('problems', models.CharField(max_length=50)),
                ('prescription', models.CharField(max_length=50)),
            ],
        ),
    ]
