# Generated by Django 4.1 on 2022-09-04 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_alter_doc_username_alter_pharma_username_and_more'),
        ('medhistory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medhistory',
            name='doctorId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='register.doc'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medhistory',
            name='patientId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='register.user'),
            preserve_default=False,
        ),
    ]
