# Generated by Django 4.1 on 2022-10-13 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_doc_image'),
        ('medhistory', '0002_medhistory_doctorid_medhistory_patientid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medhistory',
            name='doctorId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.doc', to_field='username'),
        ),
        migrations.AlterField(
            model_name='medhistory',
            name='patientId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.user', to_field='username'),
        ),
    ]
