# Generated by Django 4.1 on 2022-10-02 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('med_name', models.CharField(max_length=100, unique=True)),
                ('price', models.IntegerField()),
                ('qty', models.IntegerField(max_length=250, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='medicine/medicine_img')),
                ('description', models.TextField(max_length=500, null=True)),
            ],
        ),
    ]
