# Generated by Django 4.1 on 2022-10-03 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='med_name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='price',
            field=models.IntegerField(max_length=250),
        ),
    ]
