# Generated by Django 4.1 on 2022-09-03 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0006_alter_doc_username_alter_pharma_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='hos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Addr', models.CharField(max_length=200)),
                ('no_of_beds', models.IntegerField()),
                ('no_of_doctors', models.IntegerField()),
                ('no_of_staff', models.BigIntegerField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.doc')),
            ],
        ),
    ]
