# Generated by Django 4.1 on 2022-09-25 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_alter_hos_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hos',
            name='Name',
            field=models.CharField(max_length=200),
        ),
    ]
