# Generated by Django 4.1 on 2022-09-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('symptom_1', models.CharField(max_length=50)),
                ('symptom_2', models.CharField(max_length=50)),
                ('symptom_3', models.CharField(max_length=50)),
            ],
        ),
    ]
